version: '3.87'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./mongo:/data/db
    ports:
      - 27017:27017

  backend:
    build: ./backend
    ports:
      - 12345:12345
    depends_on:
      - mongodb
    
    